import type { DocumentoBase } from "./types";

export function simulateAnalysis(nombre: string): DocumentoBase[] {
  const now = new Date().toISOString();
  const base: DocumentoBase[] = [
    {
      id: "EXP-2025-001",
      tipoUnidad: "Expediente",
      codigoExpediente: "EXP-2025-001",
      tituloAsunto: "Actas del Consejo Directivo 2025",
      serie: "ACTAS DE SESIONES",
      subserie: "Actas",
      tipoDocumental: "Expediente",
      productor: "Consejo Directivo",
      fechaDoc: "2025-06-10",
      fechaIni: "2025-01-10",
      fechaFin: "2025-06-28",
      folios: 122,
      soporte: "Papel",
      confidencial: false,
      ubicacionFisica: "AC / Est.3 / B.2",
      observaciones: `Analizado desde ${nombre}`,
      valorPrimario: "Administrativo",
      valorSecundario: "Histórico",
      temporalidad: "Permanente",
      plazoConservacionAnios: 0,
      destinoFinal: "Conservación Permanente",
      validado: false,
      creadoPor: "IA-Pipeline",
      creadoEl: now,
    },
    {
      id: "DOC-2025-015",
      tipoUnidad: "Documento",
      codigoExpediente: "EXP-2025-001",
      tituloAsunto: "Resolución Jefatural N° 124-2025",
      serie: "RESOLUCIONES",
      subserie: "Resoluciones",
      tipoDocumental: "Resolución",
      productor: "Presidencia Ejecutiva",
      fechaDoc: "2025-06-12",
      folios: 3,
      soporte: "Papel",
      confidencial: false,
      valorPrimario: "Legal",
      valorSecundario: "Histórico",
      temporalidad: "Temporal",
      plazoConservacionAnios: 10,
      destinoFinal: "Transferencia al Archivo Central",
      validado: false,
      creadoPor: "IA-Pipeline",
      creadoEl: now,
    },
    {
      id: "DOC-2025-016",
      tipoUnidad: "Documento",
      codigoExpediente: "EXP-2025-001",
      tituloAsunto: "Expediente de denuncia administrativa 2025",
      serie: "EXPEDIENTES DE QUEJAS Y DENUNCIAS",
      subserie: "Denuncias",
      tipoDocumental: "Expediente",
      productor: "Control Centralizado",
      fechaDoc: "2025-05-28",
      folios: 48,
      soporte: "Digital",
      confidencial: false,
      valorPrimario: "Administrativo",
      valorSecundario: "Ninguno",
      temporalidad: "Temporal",
      plazoConservacionAnios: 8,
      destinoFinal: "Eliminación",
      validado: false,
      creadoPor: "IA-Pipeline",
      creadoEl: now,
    },
  ];
  return base;
}
